server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8009
  servlet:
    context-path: /

spring:
  profiles:
    include: common
  application:
    name: hxds-nebula
  cloud:
    inetutils:
      preferred-networks: 192.168.2.100
    nacos:
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 192.168.212.144:8848
        prefix: ${spring.application.name}
        namespace: hxds
      discovery:
        namespace: hxds
        username: nacos
        password: nacos
        server-addr: 192.168.212.144:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://192.168.212.144:8765;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1
      max-active: 8
      min-idle: 4
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.aomsir.hxds.nebula.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.aomsir.hxds.nebula.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000